### ISSUE TITLE
Block G parking lights

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#18]
### Property Details

Block G

### Contact Details

Directors

### Type of problem?

Repair

### Since when this issue started?

Few months 

### Issue Description?

Block G parking area is pitch dark. There are three lights there but all three are out. As per residents this has been reports many times before but no action so far. Could you please have a look and get this sorted asap. 

![2F6CBB10-0ACB-4E0B-90A6-D39A1C18E46A](https://user-images.githubusercontent.com/85579935/152063622-6e943df0-2e53-490b-964d-fc4699cef91d.jpeg)
![DC3449B3-9F10-47FC-A0D9-D293812D1280](https://user-images.githubusercontent.com/85579935/152063632-f388f518-767c-4d96-85a4-af6a66862ce6.jpeg)

### Logged By

Directors

**Comment by jeremydoran** [comment]
I believe these lights were fixed previously, I have asked a contractor to attend to this asap.

**Comment by jeremydoran** [comment]
The contractor has advised they will be attending today and will provide an update after the visit.

**Comment by jeremydoran** [comment]
Please see report below following the recent visit this week;

Our electrician re-attended site and advised the lampposts have tripped again.

Unfortunately its not a straight forward job as each lamppost has a cable that leads to it and goes to a box underneath the ground. Unless we know where this is then would have to dig up and the problem is within the box.

We are going to have to run a new circuit from the bin shed to the lights to these up and running, I will get this done asap.

Please note; the cable will go around the side of the car park.

I have asked the contractor to proceed with this asap.

**Comment by jeremydoran** [comment]
The contractor will now be going back this Thursday to proceed with this.

**Comment by jeremydoran** [comment]
The contractor has attended and believes the issue has now been resolved. 

Please could someone check this in the evening time and confirm.

**Comment by theparksilford** [comment]
I’ll check tonight.

**Comment by theparksilford** [comment]
Nope. Not fixed. Same as before. All lights out.

**Comment by theparksilford** [comment]
Is this fixed?

**Comment by jeremydoran** [comment]
This has now been fixed and should be working correctly.

**Comment by theparksilford** [comment]
This is not fixed please update what’s next.

**Comment by jeremydoran** [comment]
This has been booked to take place on Monday 25th April.

**Comment by jeremydoran** [comment]
The contractor attended and erected a mobile tower, replaced 3No bulbs and left in working order.

All works are complete.
